export const INCRIMENT_Data = "INCRIMENT_Data"
export const DECRIMENT_Data = "DECRIMENT_Data" 

export const GET_MEDICINES = "GET_MEDICINES"


export const LOADING_MEDICINES = "LOADING_MEDICINES"
export const ERROR_MEDICINES = "ERROR_MEDICINES"



export const EMAIL_VARIFICATION ="EMAIL_VARIFICATION"
export const AUTH_LOGIN = "AUTH_LOGIN"